on:
  push:
    tags:
      - 'v*'

jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
      - name: Clone repository
        uses: actions/checkout@v2
      - name: Build add-on
        run: make all
      - name: Save built add-on
        uses: actions/upload-artifact@v2
        with:
          name: dist
          path: dist
          retention-days: 30
  release:
    runs-on: ubuntu-20.04
    needs: build
    steps:
      - name: Get git information
        id: git_info
        run: echo ::set-output name=SOURCE_TAG::${GITHUB_REF#refs/tags/}
      - name: Create GitHub release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: ${{ steps.git_info.outputs.SOURCE_TAG }}
          body: ''
      - name: Download built add-on for release
        uses: actions/download-artifact@v2
        with:
          name: dist
          path: dist
      - name: Upload cesky_slovnik_pro_kontrolu_pravopisu
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: dist/cesky_slovnik_pro_kontrolu_pravopisu.xpi
          asset_name: cesky_slovnik_pro_kontrolu_pravopisu.xpi
          asset_content_type: application/x-xpinstall
      - name: Upload cesky_slovnik_pro_kontrolu_pravopisu_bez_diakritiky
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: dist/cesky_slovnik_pro_kontrolu_pravopisu_bez_diakritiky.xpi
          asset_name: cesky_slovnik_pro_kontrolu_pravopisu_bez_diakritiky.xpi
          asset_content_type: application/x-xpinstall
