name: Release

on:
  push:
    tags:
      - 'v*'

jobs:
  build:
    uses: ./.github/workflows/build.yml
    with:
      checkout_ref: ${{ github.ref }}
  release:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    needs: build
    steps:
      - name: Download built add-on for release
        uses: actions/download-artifact@v3
        with:
          name: ${{ needs.build.outputs.artifact_name }}
          path: dist
      - name: Prepare release packages
        run: |
          shopt -s globstar
          cp ./dist/**/*.xpi .
          ls -l .
      - name: Create GitHub release
        uses: softprops/action-gh-release@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          tag_name: ${{ github.ref }}
          files: |
            *.xpi
          fail_on_unmatched_files: true
          draft: false
          prerelease: false
